Þ•    F      L  a   |                      $     :     R     n     ˆ     ¤     ¼  B   Ô       
   *  ¦   5     Ü     è  7   ú     2     D     [     n     ~     “     ¥     µ     É     â  £   ÿ     £	  
   ´	  "   ¿	     â	  	   
  2   
  4   >
     s
     
  
   ¢
  	   ­
      ·
  d   Ø
     =     N     h  L   }  G   Ê          (     1     E     V     j  &   †  
   ­  À   »     |
  6   
  D   Æ
  1     	   =     G  !   N  L   p  -   ½  &   ë  C     <   V     “     œ     ¥  Æ  «     r          –     ¬     Ä     à     ÷          1  C   G  #   ‹  
   ¯  Ò   º          œ  5   ¯     å     ý          "     :     X     q     ƒ  #      '   Ä  ¶   ì     £     ¸  )   Ê  )   ô  
     I   )  D   s  !   ¸     Ú     ñ        /     j   @     «     ¿     Ý  X   ó  N   L     ›     ¸  $   Å     ê  %   	  '   /  -   W     …  ë   •       ?   —  B   ×  M     	   h     r  8   {  X   ´  6   
  (   D  T   m  B   Â                        )   B   #       7      ;          2   D               4              6   (      >           1      8          +          '             %   
   &      -       C       $              3          <                        /   *   E      	   !   ,   .   :   A   "               F   
       @                      5         9      =   0      ?                  %1$s at %2$s (in pixels, optional) 1 day ago %d days ago 1 hour ago %d hours ago 1 minute ago %d minutes ago 1 month ago %d months ago 1 second ago %d seconds ago 1 week ago %d weeks ago 1 year ago %d years ago <strong>Cache cleared!</strong> You succesfully cleared the cache. Admins only notice Appearance Because fetching posts from Facebook is relatively slow the posts are cached for <strong>30 minutes</strong>. You can manually clear the cache using the button below. Clear Cache Connection error: Did you <a href="%s">configure the plugin</a> properly? Don't show images Donate $10, $20 or $50 Donate with PayPal Excerpt length: Facebook Posts Cache Facebook Settings Facebook error: Find us on Facebook Get your App ID from %s. Get your App Secret from %s. I spent a lot of time developing this plugin and offering support for it. If you like it, consider supporting this plugin by donating a token of your appreciation. Image dimensions Image size Leave a %s review on WordPress.org Leave empty for default sizing Link text Lists a number of your most recent Facebook posts. Lists most recent posts from a public Facebook page. Load some default styles? Looking for support? Max Height Max Width No recent Facebook posts to show Not sure how to proceed? Please take a close look at the <a href="%s">installation instructions</a>. Number of posts: Open links in new window? Other Useful plugins Please fill in the Facebook Settings fields after creating your application. Please use the <a href="%s">plugin support forums</a> on WordPress.org. Recent Facebook Posts Settings Show comment count? Show like count? Show link previews? Show link to Facebook page? Some other ways to support this plugin Some time ago Take a close look at the <a href="%s">installation instructions</a> for help configuring the plugin and registering your own Facebook application, which is required to get this plugin to work. Test Configuration Test your plugin configuration using the button below. The following error was encountered when testing your configuration. This plugin needs a Facebook application to work. Thumbnail Title: Tweet about Recent Facebook Posts Use <a href="%s">this tool</a> to find the numeric ID of your Facebook page. Vote "works" on the WordPress.org plugin page Write about the plugin from your blog. You need to <a href="%s">configure Recent Facebook Posts</a> first. Your configuration seems to be okay and working. Nice work!. comments just now likes Project-Id-Version: Recent Facebook Posts 2.0.3
Report-Msgid-Bugs-To: https://wordpress.org/support/plugin/recent-facebook-posts
POT-Creation-Date: 2014-09-22 11:26:55+00:00
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
PO-Revision-Date: 2014-10-31 11:14-0000
Last-Translator: Jonadabe <jonadabe@hotmail.com>
Language-Team: 
X-Generator: Poedit 1.5.7
Plural-Forms: nplurals=2; plural=n != 1;
X-Poedit-Basepath: .
X-Poedit-SourceCharset: UTF-8
X-Poedit-KeywordsList: __;_e;_x:1,2c;_ex:1,2c;_n:1,2; _nx:1,2,4c;_n_noop:1,2;_nx_noop:1,2,3c;esc_attr__; esc_html__;esc_attr_e; esc_html_e;esc_attr_x:1,2c; esc_html_x:1,2c
X-Textdomain-Support: yes
X-Poedit-SearchPath-0: .
 %1$s de %2$s (em pixÃ©is, opcional) HÃ¡ 1 dia HÃ¡ %d dias HÃ¡ 1 hora HÃ¡ %d horas HÃ¡ 1 minuto HÃ¡ %d minutos HÃ¡ 1 mÃªs HÃ¡ %d mÃªs HÃ¡ 1 segundo HÃ¡ %d segundos HÃ¡ 1 semana HÃ¡ %d semanas HÃ¡ 1 ano HÃ¡ %d anos <strong>Cache eliminada!</strong> Eliminou com sucesso a sua cache. Notificar apenas os administradores AparÃªncia Uma vez que recolher os artigos do Facebook pode tornar lento todo o processo, os artigos sÃ£o colocados em cache durante <strong>30 minutos</strong>. Pode eliminar a cache manualmente por usar o botÃ£o abaixo. Eliminar Cache Erro de ligaÃ§Ã£o: Configurou o <a href="%s">plugin</a> apropriadamente? NÃ£o apresentar imagens Doar $10, $20 ou $50 Doar com PayPal Comprimento do excerto: Cache dos artigos do Facebook DefiniÃ§Ãµes do Facebook Erro do Facebook: Liga-te connosco no Facebook Busque a sua App ID neste local %s. Busque a sua App Secret neste local %s. Eu passei uma quantidade de tempo a desenvolver este plugin e a oferecer suporte para ele. Se gosta dele, considere suportar este plugin por doar apenas um pouco da sua apreciaÃ§Ã£o. DimensÃµes da imagem Tamanho da imagem Deixar um %s comentÃ¡rio no Wordpress.org Deixar vazio para dimensionamento padrÃ£o Texto link Listar um nÃºmero determinado dos seus mais recentes artigos do Facebook. Listar os artigos mais recentes de uma pÃ¡gina pÃºblica do Facebook. Abrir alguns estilos css padrÃ£o? Ã€ procura de suporte? Altura mÃ¡xima Largura mÃ¡xima Nenhum post recente no Facebook para apresentar NÃ£o tem a certeza de como prosseguir? Por favor atente Ã s <a href="%s">instruÃ§Ãµes de instalaÃ§Ã£o</a>. NÃºmero de artigos: Abrir links numa nova janela? Outros plugins Ãºteis Por favor preencha os campos das definiÃ§Ãµes do Facebook apÃ³s criar a sua aplicaÃ§Ã£o. Por favor use o <a href="%s">fÃ³rum de suporte do plugin</a> no WordPress.org. Artigos recentes no Facebook DefiniÃ§Ãµes Apresentar contagem de comentÃ¡rios? Apresentar contagem de gostos? Apresentar previsualizaÃ§Ã£o do link? Apresentar link da pÃ¡gina no Facebook? Algumas outras formas de suportar este plugin HÃ¡ algum tempo Verifique atentamente as <a href="%s">instruÃ§Ãµes de instalaÃ§Ã£o</a> apenas em inglÃªs, para o ajudar a configurar e a registar a sua prÃ³pria aplicaÃ§Ã£o no Facebook, o que Ã© obrigatÃ³rio para que este plugin funcione corretamente. Testar configuraÃ§Ã£o Testar a configuraÃ§Ã£o do seu plugin por usar o botÃ£o abaixo. O seguinte erro foi encontrado aquando do teste de configuraÃ§Ã£o. Este plugin precisa de uma aplicaÃ§Ã£o (application) Facebook para funcionar. Miniatura TÃ­tulo: Tweetar acerca deste plugin Artigos Recentes do Facebook Use <a href="%s">esta ferramenta</a> para encontrar o seu ID da sua pÃ¡gina de Facebook. Votar "funciona" na pÃ¡gina do plugin no WordPress.org Escreva acerca deste plugin no seu blog. Ã‰ necessÃ¡rio <a href="%s">configurar os artigos recentes do Facebook</a> primeiro. A sua configuraÃ§Ã£o parece estar bem e a funcionar. Bom trabalho! comentÃ¡rios agora mesmo gostos 
